// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ankjwtmwclzqvgpjkeyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFua2p3dG13Y2x6cXZncGprZXlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMjM4NTAsImV4cCI6MjA1OTc5OTg1MH0.wZg89JGEJGTEhXw3M00y3uPiwx928ZAX1IryFC54N-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);