// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aorcptmwdxtedrkhxtfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvcmNwdG13ZHh0ZWRya2h4dGZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5Njk4MzUsImV4cCI6MjA1OTU0NTgzNX0.RXyZW3clhBFuwGink6RCdixxm4R0RqFJAZYA5l-wJmw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);